### ISSUE TITLE
Can't get Affinity running

### ISSUE THREAD

**Issue by enesbala5** [mrshmllow/affinity-nix#71]
**Checklist**

- [x] I read the FAQ section on the README

**Describe the bug**
Running Affinity doesn't work - also I noticed that the microsoft studio download failed with status 443 - guessing that may cause a problem with the rest of the system.

**To Reproduce**

1. Install with home-manager
2. Run affinity-v3
3. Complete initial install
4. Try to run it with "affinity-v3"

**Expected behavior**
App should open

**Screenshots**

**Environment**

- OS: NixOS 25.05
- Home Manager: Release 25.05

**Additional context**
Error:

```nix
affinity-v3                                                                                                                          ─╯
+ export LC_ALL=C
+ LC_ALL=C
+ export SSL_CERT_FILE=/nix/store/4h13hlck4azq0hs6d0nnbn9kyapxvnx4-nss-cacert-3.115/etc/ssl/certs/ca-bundle.crt
+ SSL_CERT_FILE=/nix/store/4h13hlck4azq0hs6d0nnbn9kyapxvnx4-nss-cacert-3.115/etc/ssl/certs/ca-bundle.crt
+ export PATH=/nix/store/lqzs8p1ffzc58mjwh5g7dabjznqj49ma-zenity-4.1.90/bin:/nix/store/8ggin0y50drxqzlkci4p71v2nan6gc7s-curl-8.14.1-bin/bin:/nix/store/8ksax0a2mxglr5hlkj2dzl556jx7xqn5-coreutils-9.7/bin:/nix/store/pmhkmqy0vxk47r6ndh0azybhf6gs6k25-gnused-4.9/bin:/nix/store/vlckk0vnmawq9wwh7ndkrwxlpv4h29yh-gnugrep-3.12/bin:/nix/store/94ypzwhgg9y4vagg92zrjwrznih6vb2j-wget-1.25.0/bin:/nix/store/3v58nb3cwghbi986nia32i4vrksn6ipl-busybox-1.36.1/bin
+ PATH=/nix/store/lqzs8p1ffzc58mjwh5g7dabjznqj49ma-zenity-4.1.90/bin:/nix/store/8ggin0y50drxqzlkci4p71v2nan6gc7s-curl-8.14.1-bin/bin:/nix/store/8ksax0a2mxglr5hlkj2dzl556jx7xqn5-coreutils-9.7/bin:/nix/store/pmhkmqy0vxk47r6ndh0azybhf6gs6k25-gnused-4.9/bin:/nix/store/vlckk0vnmawq9wwh7ndkrwxlpv4h29yh-gnugrep-3.12/bin:/nix/store/94ypzwhgg9y4vagg92zrjwrznih6vb2j-wget-1.25.0/bin:/nix/store/3v58nb3cwghbi986nia32i4vrksn6ipl-busybox-1.36.1/bin
++ [[ -z /home/e/.local/share ]]
++ echo /home/e/.local/share/affinity-v3
+ '[' '!' -f '/home/e/.local/share/affinity-v3/drive_c/Program Files/Affinity/Affinity/Affinity.exe' ']'
+ /nix/store/ssg5ymc0d9gsdnr2pwn89fgyqk3abs0k-affinity-v3-gui-check/bin/affinity-v3-gui-check
+ tricksInstalled=0
+ type=v3
+ verbs=('dotnet48' 'corefonts' 'vcrun2022' 'allfonts')
+ declare -a verbs
++ [[ -z /home/e/.local/share ]]
++ echo /home/e/.local/share/affinity-v3
+ '[' '!' -f /home/e/.local/share/affinity-v3/.revision ']'
++ [[ -z /home/e/.local/share ]]
++ echo /home/e/.local/share/affinity-v3
+ content=1
+ [[ 1 -gt 1 ]]
+ [[ v3 == v2 ]]
++ /nix/store/cg4rgsrj8c174r8h2wn2d5gahscxnljk-affinity-winetricks/bin/affinity-winetricks list-installed
Executing cd /nix/store/6jxd6lfb8d9qlykymkjsiy6y30b0gkx5-winetricks-20250102/bin
------------------------------------------------------
warning: Unknown file arch of /nix/store/r9l3vmcgq45wq7mkbkw2s2s9ljyc906v-wine-symlink/bin/wine.
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: WoW64 type could not be detected.
------------------------------------------------------
+ installed_tricks=$'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ for verb in "${verbs[@]}"
+ echo $'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ grep -qw dotnet48
+ for verb in "${verbs[@]}"
+ echo $'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ grep -qw corefonts
+ for verb in "${verbs[@]}"
+ echo $'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ grep -qw vcrun2022
+ for verb in "${verbs[@]}"
+ echo $'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ grep -qw allfonts
+ '[' 0 -eq 1 ']'
+ '[' '' '!=' --verbose ']'
+ export WINEDEBUG=-all,fixme-all
+ WINEDEBUG=-all,fixme-all
++ [[ -z /home/e/.local/share ]]
++ echo /home/e/.local/share/affinity-v3
+ /nix/store/wp2wwg94rv220hf395wrz4llspdlx4kx-affinity-wine/bin/affinity-wine '/home/e/.local/share/affinity-v3/drive_c/Program Files/Affinity/Affinity/Affinity.exe'
* Assertion at /var/hostdir/mono/mono/metadata/object.c:4677, condition `is_ok (error)' not met, function:prepare_run_main, Could not set up parent class, due to: Could not load type of field 'Serif.Affinity.Application:<CurrentMicrosoftStorePrices>k__BackingField' (21) due to: Could not load file or assembly 'Windows.Services.Store.StoreContract, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:Z:\home\e\.local\share\affinity-v3\drive_c\Program Files\Affinity\Affinity\Serif.Affinity.dll type:Application member:(null) assembly:Z:\home\e\.local\share\affinity-v3\drive_c\Program Files\Affinity\Affinity\Affinity.exe type:Application member:(null)
```

**Comment by worldofjoni** [comment]
I have the same problem.

**Comment by worldofjoni** [comment]
Also mentioned in https://github.com/mrshmllow/affinity-nix/issues/69#issuecomment-3473598592

**Comment by mrshmllow** [comment]
This should be fixed in https://github.com/mrshmllow/affinity-nix/commit/1bf923f8853817dd5ee565d550da56ed889a2fb0

**Comment by worldofjoni** [comment]
I am still getting the same error. Reinstalling / removing the `.local/share/affinity*` did not help.

**Comment by enesbala5** [comment]
I reinstalled as well - updated the flake inputs, went through the whole setup...

I'm getting this error:

```nix
affinity-v3                                                                                                     ─╯
+ export LC_ALL=C
+ LC_ALL=C
+ export SSL_CERT_FILE=/nix/store/4h13hlck4azq0hs6d0nnbn9kyapxvnx4-nss-cacert-3.115/etc/ssl/certs/ca-bundle.crt
+ SSL_CERT_FILE=/nix/store/4h13hlck4azq0hs6d0nnbn9kyapxvnx4-nss-cacert-3.115/etc/ssl/certs/ca-bundle.crt
+ export PATH=/nix/store/lqzs8p1ffzc58mjwh5g7dabjznqj49ma-zenity-4.1.90/bin:/nix/store/8ggin0y50drxqzlkci4p71v2nan6gc7s-curl-8.14.1-bin/bin:/nix/store/8ksax0a2mxglr5hlkj2dzl556jx7xqn5-coreutils-9.7/bin:/nix/store/pmhkmqy0vxk47r6ndh0azybhf6gs6k25-gnused-4.9/bin:/nix/store/vlckk0vnmawq9wwh7ndkrwxlpv4h29yh-gnugrep-3.12/bin:/nix/store/94ypzwhgg9y4vagg92zrjwrznih6vb2j-wget-1.25.0/bin:/nix/store/3v58nb3cwghbi986nia32i4vrksn6ipl-busybox-1.36.1/bin
+ PATH=/nix/store/lqzs8p1ffzc58mjwh5g7dabjznqj49ma-zenity-4.1.90/bin:/nix/store/8ggin0y50drxqzlkci4p71v2nan6gc7s-curl-8.14.1-bin/bin:/nix/store/8ksax0a2mxglr5hlkj2dzl556jx7xqn5-coreutils-9.7/bin:/nix/store/pmhkmqy0vxk47r6ndh0azybhf6gs6k25-gnused-4.9/bin:/nix/store/vlckk0vnmawq9wwh7ndkrwxlpv4h29yh-gnugrep-3.12/bin:/nix/store/94ypzwhgg9y4vagg92zrjwrznih6vb2j-wget-1.25.0/bin:/nix/store/3v58nb3cwghbi986nia32i4vrksn6ipl-busybox-1.36.1/bin
++ [[ -z /home/e/.local/share ]]
++ echo /home/e/.local/share/affinity-v3
+ '[' '!' -f '/home/e/.local/share/affinity-v3/drive_c/Program Files/Affinity/Affinity/Affinity.exe' ']'
+ /nix/store/4cgl6ws84wiqsbbk09w9vg0w9r6n98ip-affinity-v3-gui-check/bin/affinity-v3-gui-check
+ tricksInstalled=0
+ type=v3
+ verbs=('dotnet48' 'corefonts' 'vcrun2022' 'allfonts')
+ declare -a verbs
++ [[ -z /home/e/.local/share ]]
++ echo /home/e/.local/share/affinity-v3
+ '[' '!' -f /home/e/.local/share/affinity-v3/.revision ']'
++ [[ -z /home/e/.local/share ]]
++ echo /home/e/.local/share/affinity-v3
+ content=2
+ [[ 2 -gt 2 ]]
+ [[ v3 == v2 ]]
++ /nix/store/kz6x13j3jkl98zp7l32qmmj3icfimc01-affinity-winetricks/bin/affinity-winetricks list-installed
Executing cd /nix/store/6jxd6lfb8d9qlykymkjsiy6y30b0gkx5-winetricks-20250102/bin
------------------------------------------------------
warning: Unknown file arch of /nix/store/r9l3vmcgq45wq7mkbkw2s2s9ljyc906v-wine-symlink/bin/wine.
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: WoW64 type could not be detected.
------------------------------------------------------
+ installed_tricks=$'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ for verb in "${verbs[@]}"
+ echo $'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ grep -qw dotnet48
+ for verb in "${verbs[@]}"
+ echo $'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ grep -qw corefonts
+ for verb in "${verbs[@]}"
+ echo $'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ grep -qw vcrun2022
+ for verb in "${verbs[@]}"
+ echo $'Using winetricks 20250102 - sha256sum: d0fb8bb26d1f497150406fa01d81132fd1a78a6cdc7310d38c5dfd9d315f033d with wine-9.14 and WINEARCH=win64\nrenderer=vulkan\nremove_mono internal\nremove_mono internal\nwinxp\ndotnet40\ndotnet48\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\nvcrun2022\nandale\narial\nbaekmuk\ncalibri\ncambria\ncandara\ncomicsans\nconsolas\nconstantia\ncorbel\nandale\narial\ncomicsans\ncourier\ngeorgia\nimpact\ntimes\ntrebuchet\nverdana\nwebdings\ncorefonts\ncourier\ndroid\neufonts\ngeorgia\nimpact\nipamona\nliberation\nlucida\nmeiryo\nmicross\nopensymbol\nsourcehansans\ntahoma\ntakao\ntimes\ntrebuchet\nuff\nunifont\nverdana\nvlgothic\nwebdings\nwenquanyi\nwenquanyizenhei\nallfonts'
+ grep -qw allfonts
+ '[' 0 -eq 1 ']'
+ '[' '' '!=' --verbose ']'
+ export WINEDEBUG=-all,fixme-all
+ WINEDEBUG=-all,fixme-all
++ [[ -z /home/e/.local/share ]]
++ echo /home/e/.local/share/affinity-v3
+ /nix/store/qc7w54p1pvpbx28g8d26lwnja5kmgn3z-affinity-wine/bin/affinity-wine '/home/e/.local/share/affinity-v3/drive_c/Program Files/Affinity/Affinity/Affinity.exe'
* Assertion at /var/hostdir/mono/mono/metadata/object.c:4677, condition `is_ok (error)' not met, function:prepare_run_main, Could not set up parent class, due to: Could not load type of field 'Serif.Affinity.Application:<CurrentMicrosoftStorePrices>k__BackingField' (21) due to: Could not load file or assembly 'Windows.Services.Store.StoreContract, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:Z:\home\e\.local\share\affinity-v3\drive_c\Program Files\Affinity\Affinity\Serif.Affinity.dll type:Application member:(null) assembly:Z:\home\e\.local\share\affinity-v3\drive_c\Program Files\Affinity\Affinity\Affinity.exe type:Application member:(null)
```

**Comment by mrshmllow** [comment]
I can't reproduce this anymore.. Can you show `$ ls /home/e/.local/share/affinity-v3/drive_c/windows/system32/WinMetadata/`?

**Comment by mrshmllow** [comment]
According to someone else who had this problem, this should be fixed now.

**Comment by mcsimw** [comment]
> According to someone else who had this problem, this should be fixed now.

I am going to test it now, just deleted the ~/.local/share/affinity-v3 dir first in case. 

This will take a bit of time.

**Comment by mcsimw** [comment]
> According to someone else who had this problem, this should be fixed now.

Works for me and I think it is safe to close this issue because I was able to reproduce this issue before your recent commits. Anyways Tysm!
